#!/bin/bash

index=0

rpiList=("rpi01" "rpi02" "rpi03" "rpi04" "rpi05" "rpi06" "rpi07" "rpi08" "rpi09" "rpi10" "rpi11" "rpi12" "rpi13" "rpi14" "rpi15" "rpi16" "rpi17" "rpi18")

for n in {1..18}
do
	ping -c 1 -w 1 ${rpiList[index]} > nul

	if  [ $? -eq 0 ]
	then
		echo ${rpiList[index]} : alive
	else
		echo ${rpiList[index]} : dead
	fi

	index=$((index+1))

done

